### ISSUE TITLE
[Feature request] Allow having a lint line offset

### ISSUE THREAD

**Issue by itaranto** [mfussenegger/nvim-lint#354]
I'm writing a `json` parser using `jq`, and I came up with the following configuration:

```lua
    lint.linters.jq = {
      name = 'jq',
      cmd = 'jq',
      stdin = true,
      stream = 'stderr',
      ignore_exitcode = true,
      parser = require('lint.parser').from_pattern(
        '^(.*): (.+) at line (%d+), column (%d+)$',
        { 'code', 'message', 'lnum', 'col' },
        nil,
        nil,
        nil
      ),
    }
```

An example `jq` error message would be: `parse error: Expected another key-value pair at line 27, column 1`

This works fine with the exception that the messages are shifted one line below:

![image](https://github.com/mfussenegger/nvim-lint/assets/11463919/9139b20a-95e8-4f1f-97c2-a1f452644e20)

`efm-langserver` has `lint-offset` and `lint-offset-columns` to correct line and column-wise respectively. 

An equivalent configuration for `efm-langserver` would be:

```yaml
  json-jq: &json-jq
    lint-command: 'jq'
    lint-stdin: true
    lint-offset: 1
    lint-formats:
      - '%m at line %l, column %c'
```

I wonder if those could be implemented, specially `lint-offset`.
