### ISSUE TITLE
nvim-lint throws error when issue in Phpstan baseline is fixed/changed

### ISSUE THREAD

**Issue by madflow** [mfussenegger/nvim-lint#581]
- Create a new PHP project of some sort
- Install phpstan and configure nvim-lint
- Create some phpstan error in a file
- Generate a baseline
- Open Neovim and change the code which is in the baseline

you will get:

```
 │     Parser failed. Error message:  [1, 1]
 │      ...l/share/nvim/lazy/nvim-lint/lua/lint/linters/phpstan.lua:29: attempt to perform arithmetic on field 'line' (a userdata value) 
 │       
 │      Output from linter: 
 │      {"totals":{"errors":0,"file_errors":1},"files":{"/private/tmp/actor/src/Kernel.php":{"errors":1,"messages":[{"message":"Ignored error pattern #^Method App\\\\Kernel\\:\\:fux\\(\\) has parameter \\$array with no value type specified in iterable type array\\.$# in path /private/tmp/actor/src/Kernel.php was not matched in reported errors.","line":null,"ignorable":false}]}},"errors":[]} 
```

```php
<?php

namespace App;

use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    public function fux(array $array)
    {

    }
}
```

```
# phpstan-baseline.neon
parameters:
        ignoreErrors:
                -
                        message: "#^Method App\\\\Kernel\\:\\:fux\\(\\) has no return type specified\\.$#"
                        count: 1
                        path: src/Kernel.php

                -
                        message: "#^Method App\\\\Kernel\\:\\:fux\\(\\) has parameter \\$array with no value type specified in iterable type array\\.$#"
                        count: 1
                        path: src/Kernel.php
```

![Kapture 2024-05-13 at 18 50 02](https://github.com/mfussenegger/nvim-lint/assets/183248/f168a013-c12c-4cbf-a106-0aaaf0f35fe5)
